### ISSUE TITLE
wrong working dir failures for qupd8 and qbuild

### ISSUE THREAD

**Issue by zeruth** [Joelgp83/Build-scripts-for-switchroot-android#2]
The following code at https://github.com/Joelgp83/Build-scripts-for-switchroot-android/blob/f28f4a59eefc85617eb233768d091e546c269167/qupd8.sh#L49

for me the cd had to be amended to 
```
cd ../..
```
as at that point, it is working in android/lineage instead of android

---

This same problem effects https://github.com/Joelgp83/Build-scripts-for-switchroot-android/blob/f28f4a59eefc85617eb233768d091e546c269167/qbuild.sh#L36

The instructions were quite clear to run from the switchroot_scripts dir

**Comment by Joelgp83** [comment]
Yep, definitely a typo I missed. Thanks for spotting that. Will be fixed soon.
